---
output:
    github_document:
        html_preview: false
---

# watercolours

This package contains palettes derived from watercolour artists including
X and Y.

```{r}
library(watercolours)
```

## Examples

```{r}
library(ggplot2)
ggplot(diamonds, aes(color, fill = clarity)) +
  geom_bar() +
  scale_fill_watercolour(palette = "durer")
```

```{r}
ggplot(mtcars, aes(disp, mpg, col = qsec)) +
  geom_point(size = 4) +
  scale_color_watercolour(type = "continuous")
```

The available palettes are

Anders Zorn - [*Sommarnöje*](https://en.wikipedia.org/wiki/Sommarn%C3%B6je) (1886)

```{r}
show_palette("zorn")
```

Fidelia Bridges - [*Calla Lilly*](https://www.brooklynmuseum.org/objects/1638) (1875)

```{r}
show_palette("bridges")
```

Dolla Richmond -[*Mount Egmont*](https://artsandculture.google.com/asset/mount-egmont/2AH3LhLcXldhDA) (1929)

```{r}
show_palette("richmond")
```

Albrecht Durer - [*Wing of a Blue Roller*](https://en.wikipedia.org/wiki/Wing_of_a_European_Roller) (1512)

```{r}
show_palette("durer")
```

Wassily Kandinsky - [*Delicate Tension. No. 85*](https://www.wassilykandinsky.net/work-271.php)

```{r}
show_palette("kandinsky")
```

## Installation

You can install `watercolours` from github with:

```{r, eval=FALSE, message=FALSE}
devtools::install_github("gjcooper/watercolours")
```

